### ISSUE TITLE
Q: regarding new v-analzyer repo and tree-sitter

### ISSUE THREAD

**Issue by ttytm** [vlang/v-analyzer#14]
### Describe the feature

Since the v-analzyer repo has moved: 
Before pushing an update to nvim-treesitter to match the new repo https://github.com/nvim-treesitter/nvim-treesitter/blob/b4138891b3454beeb14eef171c91c92377fcd715/lua/nvim-treesitter/parsers.lua#L2058-L2066, should tree-sitter locations be kept as they are for now, or should some re-organization be done beforhand? 

E.g., a more conventional approach with a separate repo for the tree sitter part could make sense. Imho it's a bit messy atm. and the generated files create a bit of pollution.

### Use Case

- Repository organization, statistics and size 
- Convenience for devs

**Comment by spytheman** [comment]
No, the tree sitter generated parser should stay here.

I explicitly do not want a separate master repository for it, if it can be avoided, since it makes releases and updating, have more moving parts, and thus harder.

A separate repository could be made, if it is *not used for development*, but instead just mirrors the changes made here, for the convenience of other projects.

**Comment by ttytm** [comment]
Thanks. Opened the MR at nvim-treesitter to update the url.
